name: CI/CD Pipeline

permissions:
  contents: write
  pages: write
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  document:
    needs: test
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.document.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: test
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.deploy.yml@main
    with:
      branch_name: ${{ github.ref_name }}
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
