name: Dependabot Auto-Merge Trigger

on:
  workflow_run:
    workflows: ['CI/CD Pipeline']
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.dependabot-auto-merge.yml@main
    secrets: inherit
