name: Dependabot Auto-Merge
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.dependabot-auto-merge.yml@main
    secrets: inherit
